I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 34, in script
    scene bg forest with slowfade
TypeError: Fade() takes at least 3 arguments (3 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script
    scene bg forest with slowfade
  File "C:\Users\nameless\Desktop\renpy-7.0.0-sdk\renpy\ast.py", line 1337, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\nameless\Desktop\renpy-7.0.0-sdk\renpy\exports.py", line 1452, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\nameless\Desktop\renpy-7.0.0-sdk\renpy\display\core.py", line 2207, in do_with
    clear=clear)
  File "C:\Users\nameless\Desktop\renpy-7.0.0-sdk\renpy\display\core.py", line 2649, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\nameless\Desktop\renpy-7.0.0-sdk\renpy\display\core.py", line 2986, in interact_core
    new_widget=layers_root)
  File "C:\Users\nameless\Desktop\renpy-7.0.0-sdk\renpy\curry.py", line 38, in __call__
    **dict(self.kwargs.items() + kwargs.items()))
TypeError: Fade() takes at least 3 arguments (3 given)

Windows-8-6.2.9200
Ren'Py 7.0.0.196
our_game 1.0
Tue Jul 31 20:20:50 2018
